### ISSUE TITLE
I'm gettting this error can you help me with this ?

### ISSUE THREAD

**Issue by donmbelembe** [rmxakalogistik/cordova-plugin-VoIpUSSD#1]
$ cordova run android
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=C:\Users\donmb\AndroidSdk (DEPRECATED)
Subproject Path: CordovaLib
Subproject Path: app
> Task :app:preBuild UP-TO-DATE
> Task :CordovaLib:preBuild UP-TO-DATE
> Task :CordovaLib:preDebugBuild UP-TO-DATE
> Task :CordovaLib:checkDebugManifest UP-TO-DATE
> Task :CordovaLib:processDebugManifest UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :CordovaLib:compileDebugAidl NO-SOURCE
> Task :app:compileDebugAidl NO-SOURCE
> Task :CordovaLib:packageDebugRenderscript NO-SOURCE
> Task :app:compileDebugRenderscript UP-TO-DATE
> Task :app:checkDebugManifest UP-TO-DATE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:prepareLintJar UP-TO-DATE
> Task :app:generateDebugSources UP-TO-DATE
> Task :CordovaLib:compileDebugRenderscript UP-TO-DATE
> Task :CordovaLib:generateDebugBuildConfig UP-TO-DATE
> Task :CordovaLib:generateDebugResValues UP-TO-DATE
> Task :CordovaLib:generateDebugResources UP-TO-DATE
> Task :CordovaLib:packageDebugResources UP-TO-DATE
> Task :CordovaLib:generateDebugRFile UP-TO-DATE
> Task :CordovaLib:prepareLintJar UP-TO-DATE
> Task :CordovaLib:generateDebugSources UP-TO-DATE
> Task :CordovaLib:javaPreCompileDebug UP-TO-DATE
> Task :CordovaLib:compileDebugJavaWithJavac UP-TO-DATE
> Task :CordovaLib:processDebugJavaRes NO-SOURCE
> Task :CordovaLib:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug UP-TO-DATE
> Task :app:javaPreCompileDebug UP-TO-DATE
> Task :app:mainApkListPersistenceDebug UP-TO-DATE
> Task :app:generateDebugResValues UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :app:mergeDebugResources UP-TO-DATE
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:processDebugManifest
> Task :app:processDebugResources

C:\Myproject\src-cordova\platforms\android\app\src\main\java\com\cordova\ramymokako\plugin\ussd\android\VoIpUSSD.java:6: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
C:\Myproject\src-cordova\platforms\android\app\src\main\java\com\cordova\ramymokako\plugin\ussd\android\VoIpUSSD.java:7: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
C:\Myproject\src-cordova\platforms\android\app\src\main\java\com\cordova\ramymokako\plugin\ussd\android\VoIpUSSD.java:26: error: package io.sybox.easyshare does not exist
import io.sybox.easyshare.MainActivity;
                         ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
> Task :app:compileDebugJavaWithJavac FAILED
24 actionable tasks: 3 executed, 21 up-to-date
C:\Myproject\src-cordova\platforms\android\gradlew: Command failed with exit code 1 Error output:
C:\Myproject\src-cordova\platforms\android\app\src\main\java\com\cordova\ramymokako\plugin\ussd\android\VoIpUSSD.java:6: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
C:\Myproject\src-cordova\platforms\android\app\src\main\java\com\cordova\ramymokako\plugin\ussd\android\VoIpUSSD.java:7: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
C:\Myproject\src-cordova\platforms\android\app\src\main\java\com\cordova\ramymokako\plugin\ussd\android\VoIpUSSD.java:26: error: package io.sybox.easyshare does not exist
import io.sybox.easyshare.MainActivity;
                         ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

**Comment by rmxakalogistik** [comment]
Dear @donmbelembe , you must replace `io.sybox.easyshare` by the name of your package

**Comment by donmbelembe** [comment]
Thanks it solved one issue, 2 more remaining

**Comment by donmbelembe** [comment]
$ cordova run android
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=C:\Users\donmb\AndroidSdk (DEPRECATED)
Subproject Path: CordovaLib
Subproject Path: app
Starting a Gradle Daemon (subsequent builds will be faster)
> Task :app:preBuild UP-TO-DATE
> Task :CordovaLib:preBuild UP-TO-DATE
> Task :CordovaLib:preDebugBuild UP-TO-DATE
> Task :CordovaLib:checkDebugManifest UP-TO-DATE
> Task :CordovaLib:processDebugManifest UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :CordovaLib:compileDebugAidl NO-SOURCE
> Task :app:compileDebugAidl NO-SOURCE
> Task :CordovaLib:packageDebugRenderscript NO-SOURCE
> Task :app:compileDebugRenderscript UP-TO-DATE
> Task :app:checkDebugManifest UP-TO-DATE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:prepareLintJar UP-TO-DATE
> Task :app:generateDebugSources UP-TO-DATE
> Task :CordovaLib:compileDebugRenderscript UP-TO-DATE
> Task :CordovaLib:generateDebugBuildConfig UP-TO-DATE
> Task :CordovaLib:generateDebugResValues UP-TO-DATE
> Task :CordovaLib:generateDebugResources UP-TO-DATE
> Task :CordovaLib:packageDebugResources UP-TO-DATE
> Task :CordovaLib:generateDebugRFile UP-TO-DATE
> Task :CordovaLib:prepareLintJar UP-TO-DATE
> Task :CordovaLib:generateDebugSources UP-TO-DATE
> Task :CordovaLib:javaPreCompileDebug UP-TO-DATE
> Task :CordovaLib:compileDebugJavaWithJavac UP-TO-DATE
> Task :CordovaLib:processDebugJavaRes NO-SOURCE
> Task :CordovaLib:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug UP-TO-DATE
> Task :app:javaPreCompileDebug UP-TO-DATE
> Task :app:mainApkListPersistenceDebug UP-TO-DATE
> Task :app:generateDebugResValues UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :app:mergeDebugResources UP-TO-DATE
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:processDebugManifest UP-TO-DATE
> Task :app:processDebugResources UP-TO-DATE

C:\Users\donmb\Documents\Projects\don\StoreSelfService\src-cordova\platforms\android\app\src\main\java\com\cordova\ramymokako\plugin\ussd\android\VoIpUSSD.java:6: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
C:\Users\donmb\Documents\Projects\don\StoreSelfService\src-cordova\platforms\android\app\src\main\java\com\cordova\ramymokako\plugin\ussd\android\VoIpUSSD.java:7: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
> Task :app:compileDebugJavaWithJavac
Note: Some input files use or override a deprecated API.
> Task :app:compileDebugJavaWithJavac
Note: Recompile with -Xlint:deprecation for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 1s
 FAILED
24 actionable tasks: 1 executed, 23 up-to-date
C:\Users\donmb\Documents\Projects\don\StoreSelfService\src-cordova\platforms\android\gradlew: Command failed with exit code 1 Error output:
C:\Users\donmb\Documents\Projects\don\StoreSelfService\src-cordova\platforms\android\app\src\main\java\com\cordova\ramymokako\plugin\ussd\android\VoIpUSSD.java:6: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
C:\Users\donmb\Documents\Projects\don\StoreSelfService\src-cordova\platforms\android\app\src\main\java\com\cordova\ramymokako\plugin\ussd\android\VoIpUSSD.java:7: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 1s

**Comment by donmbelembe** [comment]
So i was able to make it work after deleting the line 6 and 7 of https://github.com/rmxakalogistik/cordova-plugin-VoIpUSSD/blob/fbabd67a160cfd180e1959aa6e8a345d04197e8c/src/android/VoIpUSSD.java#L7

I found out that this plugin contains a lot of trash code

**Comment by rmxakalogistik** [comment]
Ok it is good thing you was able to run this plugin.
Thank you for the remark, i commented  the line 6 and 7 of src/android/VoIpUSSD.java and i also update the Readme section to exxplain the need to change the main package name on line 26.
Now enjoy your app.

**Comment by donmbelembe** [comment]
thanks MWANA YA MBOKA
actually I also deleted the line 26 because it is not in use. so please comment it and remove it on the readme. my app is still working after removing the 26 line

**Comment by rmxakalogistik** [comment]
Already done NDEKO, thanks for your contribution

**Comment by romellfudi** [comment]
Hi @rmxakalogistik, @donmbelembe , does this plugin work very well?

**Comment by rmxakalogistik** [comment]
Hi @romellfudi , yes it work very well.

**Comment by romellfudi** [comment]
Hi again @rmxakalogistik , i added references of your repository and issue-link in [the repository](https://github.com/romellfudi/VoIpUSSD#cordova-plugin)
